export const pickupLines = {
  lines: [
    'Are you from Middle Earth? Because you’ve got me under your spell.',
    'Do you believe in destiny? Because I’m convinced we’re meant to be.',
    'Do you have a magic wand? Because you’ve cast a spell on me.',
    'Is your name Scarlett? Because you’ve got me Gone with the Wind.',
    'Do you believe in love at first line? Because I was smitten with you from the moment I heard you speak.',
    'Are you from Hogwarts? Because you’ve got me under your spell.',
    'Do you believe in fate? Because I think we’re two peas in a pod.',
    'Do you have a time machine? Because I can’t imagine my future without you.',
    'Is your name Katniss? Because you’ve got me on fire.',
    'Do you believe in love at first shot? Because I was hit by Cupid’s arrow the moment I saw you.',
    'Are you from Narnia? Because you’ve got me under your spell.',
    'Do you believe in destiny? Because I think we’re meant to be together.',
    'Do you have a map of the galaxy? Because I want to explore the universe with you.',
    'Is your name Indiana? Because you’ve got me on a treasure hunt.',
    'Do you believe in love at first kiss? Because I can’t imagine my future without your lips pressed against mine.',
    'Are you from Westeros? Because you’ve got me under your spell.',
    'Do you believe in fate? Because I think we’re a match made in heaven.',
    'Is your name Trinity? Because you’ve got me on a journey through the Matrix.',
    'Do you believe in love at first dance? Because I can’t imagine my future without you in my arms.',
    'Are you from Neverland? Because you’ve got me under your spell.',
    'Do you believe in destiny? Because I think we’re meant to be together forever.',
    'Do you have a map of the world? Because I want to travel the world with you.',
    'Is your name Elle? Because you’ve got me Legally Blonde.',
    'Do you believe in love at first flight? Because I can’t imagine my future without you by my side.',
    'Are you from Asgard? Because you’ve got me under your spell.',
    'Do you believe in fate? Because I think we’re a match made in the stars.',
    'Do you have a map of the universe? Because I want to explore the galaxy with you.',
    'Is your name Sarah? Because you’ve got me on a Labyrinth.',
    'Do you believe in love at first song? Because I can’t imagine my future without your voice in my ear.',
    'Are you from The Land of Oz? Because you’ve got me under your spell.',
    'Do you believe in destiny? Because I think we’re a match made in fairy tale.',
    'You must be the missing piece to my puzzle, because life was incomplete until I saw you.',
    'Are you a magician? Because every time I look at you, everyone else disappears.',
    'Do you believe in love at first sight, or should I walk by again?',
    "You must be a time traveler, because I can't imagine my future without you in it.",
    'Do you have a map? Because I just got lost in your eyes.',
    "I'm not saying you're the best thing that ever happened to me, I'm saying you're the only thing that ever happened to me.",
    "I must be dreaming, because I never thought I'd find someone like you.",
    "I'm not a photographer, but I can definitely picture us together.",
    "Is your name Google? Because you have everything I've been searching for.",
    "You must be a work of art, because I can't take my eyes off of you.",
  ],
};
